#' French deck dataset
#'
#' A dataset containing a standard French deck of cards, including two optional jokers.
#'
#' @format An object of class \code{deck} with 54 cards.
#' @source Generated by \code{data-raw/deck_french.R}
"deck_french"

#' Spanish deck dataset
#'
#' A dataset containing a standard Spanish deck of 40 cards, with optional 8s and 9s.
#'
#' @format An object of class \code{deck} with 40 base cards and 8 optional cards.
#' @source Generated by \code{data-raw/deck_spanish.R}
"deck_spanish"